
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-courses-f24-03
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-03
pull_requests: [{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-issue41","number":46,"title":"TEST -- IGNORE THIS","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/46"},{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-issue36","number":45,"title":"Create frontend Fixtures for Finals","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/45"},{"author":{"id":"U_kgDOBt2F9Q","is_bot":false,"login":"bsaiju","name":""},"headRefName":"bharat-issue9","number":43,"title":"Fixes bug that allowed schedules in the same quarter to have the same name","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/43"},{"author":{"id":"U_kgDOBtzY9A","is_bot":false,"login":"pballani","name":""},"headRefName":"priyanka-duplicate-sections","number":42,"title":"replaced duplicate sections error message","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/42"}]
