
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-courses-f24-03
owner: ucsb-cs156-f24
repo_name: proj-courses-f24-03
pull_requests: [{"author":{"id":"U_kgDOBtg9vg","is_bot":false,"login":"eugeneLim628","name":""},"headRefName":"eugene-issue35","number":40,"title":"Entity and Repository classes for finals endpoint","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/40"},{"author":{"id":"U_kgDOBt2F9Q","is_bot":false,"login":"bsaiju","name":""},"headRefName":"bharat-issue8p2","number":34,"title":"Makes Description Optional on Personal Schedule","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/34"},{"author":{"id":"U_kgDOBs6HEA","is_bot":false,"login":"chloecweng","name":""},"headRefName":"chloe-issue23","number":32,"title":"UpdateTable Component (EPIC: Build Admin UI for Updates)","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/32"},{"author":{"id":"MDQ6VXNlcjQzMTg5MjU5","is_bot":false,"login":"SameerSRao","name":"Sameer Rao"},"headRefName":"Sameer-Link-Log","number":31,"title":"Add Link to Detailed Log Page","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/31"},{"author":{"id":"MDQ6VXNlcjQzMTg5MjU5","is_bot":false,"login":"SameerSRao","name":"Sameer Rao"},"headRefName":"Sameer-Detailed-Log","number":29,"title":"Detailed log page for long running jobs","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/29"},{"author":{"id":"MDQ6VXNlcjQzMTg5MjU5","is_bot":false,"login":"SameerSRao","name":"Sameer Rao"},"headRefName":"Sameer-Truncate-Log","number":27,"title":"Truncates logs of long running jobs","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/27"},{"author":{"id":"U_kgDOBs6HEA","is_bot":false,"login":"chloecweng","name":""},"headRefName":"chloe-issue21","number":24,"title":"Create AdminUpdatesPage Placeholder","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/24"},{"author":{"id":"U_kgDOBtPjyQ","is_bot":false,"login":"ChristopherChau","name":"Christopher Chau"},"headRefName":"chris-issue11","number":22,"title":"Feature: Admins can now purge job log ","url":"https://github.com/ucsb-cs156-f24/proj-courses-f24-03/pull/22"}]
